### ISSUE TITLE
Turniere Datenmodell

### ISSUE THREAD

**Issue by Synfray** [Ineffizienz/Lan#155]
Mach!

**Comment by Terrorpuschel** [comment]
Schnell

**Comment by Ineffizienz** [comment]
Fehlt nicht noch irgendwo ein Datenfeld, in dem wir den Spielmodus hinterlegen? Beispielsweise halt 1on1 oder 2on2, CTF oder irgendwas der Gleichen? Klar wird das prinzipiell über die Anzahl der Spieler in den Teams realisiert, aber für die nachträgliche Übersicht wäre vielleicht ein entsprechendes Datenfeld mit dem Spielmodus nicht so schlecht?

Wenn dem so wäre, wäre doch der sinnvollste Ort das _Turnier_, oder? @Synfray
