### ISSUE TITLE
Spieler und Turnier unique

### ISSUE THREAD

**Issue by Ineffizienz** [Ineffizienz/Lan#189]
In _tm_gamerslist_ sollte lediglich eine Kombination aus Spieler und Turnier möglich sein. Dazu muss die Kombination aus beiden **unique** sein.

**Comment by MichaelDietzel** [comment]
Die Spalte tm_id ist aktuell default NULL. Falls das nötig sein sollte, wird das vermutlich zu Problemen mit dem unique führen.
